export const CHANGE_NAME = 'change-name'
export const CHANGE_SURNAME = 'change-surname'
export const CHANGE_NICKNAME = 'change-nickname'
export const CHANGE_FACTION = 'change-faction'
export const CHANGE_STATE = 'change-state'
export const EDIT_PLAYER = 'edit-player'
